"""Added proxy

Revision ID: 9e504434792c
Revises: eeffe7d7b09f
Create Date: 2018-04-19 14:24:17.321936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e504434792c'
down_revision = 'eeffe7d7b09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('proxy_id', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=230), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('proxy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy')
    # ### end Alembic commands ###
