"""update proxy

Revision ID: c38df8b2cae7
Revises: 9e504434792c
Create Date: 2018-04-19 14:59:40.396642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38df8b2cae7'
down_revision = '9e504434792c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
